[vendor]
id = "com.audionerdz"
name = "AudioNerdz"
au_manufacturer = "xsyT"
url = "https://audionerdz.com"

[[plugin]]
name = "Delay Lama"
bundle_id = "delaylama"
crate = "xymonk"
category = "instrument"
fourcc = "DLma"
au_manufacturer = "xsyT"
au_tag = "Synthesizer"
ios_scale_editor_to_fit = true
